### ISSUE TITLE
Data usage license

### ISSUE THREAD

**Issue by JosiahParry** [correlatesstatepolicy/cspp#3]
Thank you for making such a useful package! 

Myself and my colleagues are interested in exploring the use of your data. However, we need to make sure that we are allowed to use it based on the license it is released under. While the R package is released under the GPL-3, the license does not extend to the data itself rather only the code. I also could not find any licenses for the data at  https://ippsr.msu.edu/public-policy/correlates-state-policy. 

Do you know where we can find the license of the data documented? Thanks!!

**Comment by caleblucas** [comment]
So glad to hear the package and data are useful!We compiled the data using hundreds of sources, each of which is governed by its own license. We list these in the codebook, which is available as a csv and pdf at the page you linked. Some will restrict certain types of usage.On Nov 30, 2023, at 11:55, Josiah Parry ***@***.***> wrote:﻿
Thank you for making such a useful package!
Myself and my colleagues are interested in exploring the use of your data. However, we need to make sure that we are allowed to use it based on the license it is released under. While the R package is released under the GPL-3, the license does not extend to the data itself rather only the code. I also could not find any licenses for the data at  https://ippsr.msu.edu/public-policy/correlates-state-policy.
Do you know where we can find the license of the data documented? Thanks!!

**Comment by JosiahParry** [comment]
Thanks for letting me know! Unfortunately the csv provides the sources and not the licenses. It would be wonderful if the data licenses can be added to the code book.

**Comment by caleblucas** [comment]
Yes! Exactly. Adding license information is a fantastic idea and something I can pass to the team. Thanks!On Nov 30, 2023, at 13:43, Josiah Parry ***@***.***> wrote:﻿
Thanks for letting me know! Unfortunately the csv provides the sources and not the licenses. It would be wonderful if the data licenses can be added to the code book.
